/* ==========================================
   Mock CIS Benchmark Data for Testing
   ========================================== */

export const mockAuditSession = {
  session_id: 999,
  asset_id: 1,
  asset_name: "Demo-CoreSwitch",
  target_ip: "192.168.1.1",
  device_type: "cisco",
  status: "completed",
  started_at: new Date().toISOString(),
  completed_at: new Date().toISOString(),
  duration_seconds: 45.5,
  compliance: {
    total_checks: 82,
    passed: 74,
    failed: 8,
    errors: 0,
    compliance_pct: 90.24,
    weighted_compliance_pct: 91.5
  },
  connection_error: null
};

export const mockAuditResults = [
  { id: 1, check_number: "CIS-1.1.1", check_title: "Enable 'aaa new-model'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "aaa new-model", checked_at: new Date().toISOString() },
  { id: 2, check_number: "CIS-1.1.2", check_title: "Enable 'aaa authentication login'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "aaa authentication login default", checked_at: new Date().toISOString() },
  { id: 3, check_number: "CIS-1.1.3", check_title: "Enable 'aaa authentication enable default'", severity: "high", level: "L1", status: "FAIL", evidence_snippet: "not set", checked_at: new Date().toISOString() },
  { id: 4, check_number: "CIS-1.1.4", check_title: "Set 'login authentication for 'line con 0'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "line console 0\n login authentication default", checked_at: new Date().toISOString() },
  { id: 5, check_number: "CIS-1.1.5", check_title: "Set 'login authentication for 'line tty'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "no tty lines configured", checked_at: new Date().toISOString() },
  { id: 6, check_number: "CIS-1.1.6", check_title: "Set 'login authentication for 'line vty'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "line vty 0 4\n login authentication default", checked_at: new Date().toISOString() },
  { id: 7, check_number: "CIS-1.1.7", check_title: "Set 'aaa accounting' to log all privileged use commands using 'commands 15'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "aaa accounting commands 15 default", checked_at: new Date().toISOString() },
  { id: 8, check_number: "CIS-1.1.8", check_title: "Set 'aaa accounting connection'", severity: "medium", level: "L1", status: "FAIL", evidence_snippet: "not set", checked_at: new Date().toISOString() },
  { id: 9, check_number: "CIS-1.1.9", check_title: "Set 'aaa accounting exec'", severity: "medium", level: "L1", status: "FAIL", evidence_snippet: "not set", checked_at: new Date().toISOString() },
  { id: 10, check_number: "CIS-1.1.10", check_title: "Set 'aaa accounting network'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "aaa accounting network default", checked_at: new Date().toISOString() },
  { id: 11, check_number: "CIS-1.1.11", check_title: "Set 'aaa accounting system'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "aaa accounting system default", checked_at: new Date().toISOString() },
  { id: 12, check_number: "CIS-1.2.1", check_title: "Set 'privilege 1' for local users", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "username admin privilege 15", checked_at: new Date().toISOString() },
  { id: 13, check_number: "CIS-1.2.2", check_title: "Set 'transport input ssh' for 'line vty' connections", severity: "high", level: "L1", status: "PASS", evidence_snippet: "transport input ssh", checked_at: new Date().toISOString() },
  { id: 14, check_number: "CIS-1.2.4", check_title: "Create 'access-list' for use with 'line vty'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "ip access-list standard 10", checked_at: new Date().toISOString() },
  { id: 15, check_number: "CIS-1.2.5", check_title: "Set 'access-class' for 'line vty'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "access-class 10 in", checked_at: new Date().toISOString() },
  { id: 16, check_number: "CIS-1.3.1", check_title: "Set the 'banner-text' for 'banner exec'", severity: "low", level: "L1", status: "PASS", evidence_snippet: "banner exec", checked_at: new Date().toISOString() },
  { id: 17, check_number: "CIS-1.3.2", check_title: "Set the 'banner-text' for 'banner login'", severity: "low", level: "L1", status: "PASS", evidence_snippet: "banner login", checked_at: new Date().toISOString() },
  { id: 18, check_number: "CIS-1.3.3", check_title: "Set the 'banner-text' for 'banner motd'", severity: "low", level: "L1", status: "PASS", evidence_snippet: "banner motd", checked_at: new Date().toISOString() },
  { id: 19, check_number: "CIS-1.4.1", check_title: "Set 'password' for 'enable secret'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "enable secret 5 <REDACTED>", checked_at: new Date().toISOString() },
  { id: 20, check_number: "CIS-1.4.2", check_title: "Enable 'service password-encryption'", severity: "low", level: "L1", status: "PASS", evidence_snippet: "service password-encryption", checked_at: new Date().toISOString() },
  { id: 21, check_number: "CIS-1.4.3", check_title: "Set 'username secret' for all local users", severity: "high", level: "L1", status: "FAIL", evidence_snippet: "username admin password 7 <REDACTED>", checked_at: new Date().toISOString() },
  { id: 22, check_number: "CIS-1.5.1", check_title: "Set 'no snmp-server' to disable SNMP when unused", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "SNMP not configured", checked_at: new Date().toISOString() },
  { id: 23, check_number: "CIS-2.1.1.1.1", check_title: "Set the 'hostname'", severity: "low", level: "L1", status: "PASS", evidence_snippet: "hostname CoreSwitch01", checked_at: new Date().toISOString() },
  { id: 24, check_number: "CIS-2.1.1.1.2", check_title: "Set the 'ip domain-name'", severity: "low", level: "L1", status: "PASS", evidence_snippet: "ip domain-name example.com", checked_at: new Date().toISOString() },
  { id: 25, check_number: "CIS-2.1.1.1.3", check_title: "Set 'modulus' to greater than or equal to 2048 for 'crypto key generate rsa'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "Detected key size: 2048 bit", checked_at: new Date().toISOString() },
  { id: 26, check_number: "CIS-2.1.1.1.4", check_title: "Set 'seconds' for 'ip ssh timeout'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "ip ssh timeout 60", checked_at: new Date().toISOString() },
  { id: 27, check_number: "CIS-2.1.1.1.5", check_title: "Set maximimum value for 'ip ssh authentication-retries'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "ip ssh authentication-retries 3", checked_at: new Date().toISOString() },
  { id: 28, check_number: "CIS-2.1.1.2", check_title: "Set version 2 for 'ip ssh version'", severity: "high", level: "L1", status: "PASS", evidence_snippet: "ip ssh version 2", checked_at: new Date().toISOString() },
  { id: 29, check_number: "CIS-2.1.2", check_title: "Set 'no cdp run'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "no cdp run", checked_at: new Date().toISOString() },
  { id: 30, check_number: "CIS-2.1.3", check_title: "Set 'no ip bootp server'", severity: "low", level: "L1", status: "PASS", evidence_snippet: "no ip bootp server", checked_at: new Date().toISOString() },
  { id: 31, check_number: "CIS-2.2.1", check_title: "Set 'logging on'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "logging on", checked_at: new Date().toISOString() },
  { id: 32, check_number: "CIS-2.2.4", check_title: "Set IP address for 'logging host'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "logging host 192.168.1.100", checked_at: new Date().toISOString() },
  { id: 33, check_number: "CIS-2.3.1.1", check_title: "Set 'ntp authenticate'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "ntp authenticate", checked_at: new Date().toISOString() },
  { id: 34, check_number: "CIS-2.3.2", check_title: "Set 'ip address' for 'ntp server'", severity: "low", level: "L1", status: "PASS", evidence_snippet: "ntp server 192.168.1.10", checked_at: new Date().toISOString() },
  { id: 35, check_number: "CIS-2.4.1", check_title: "Create a single 'interface loopback'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "interface Loopback0", checked_at: new Date().toISOString() },
  { id: 36, check_number: "CIS-2.4.2", check_title: "Set AAA 'source-interface'", severity: "low", level: "L1", status: "FAIL", evidence_snippet: "not set", checked_at: new Date().toISOString() },
  { id: 37, check_number: "CIS-3.1.1", check_title: "Set 'no ip source-route'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "no ip source-route", checked_at: new Date().toISOString() },
  { id: 38, check_number: "CIS-3.1.2", check_title: "Set 'no ip proxy-arp'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "no ip proxy-arp", checked_at: new Date().toISOString() },
  { id: 39, check_number: "CIS-3.1.3", check_title: "Set 'no interface tunnel'", severity: "medium", level: "L1", status: "PASS", evidence_snippet: "no tunnel interfaces (good)", checked_at: new Date().toISOString() },
  { id: 40, check_number: "CIS-3.1.4", check_title: "Set 'ip verify unicast source reachable-via'", severity: "medium", level: "L1", status: "FAIL", evidence_snippet: "uRPF not configured", checked_at: new Date().toISOString() }
];

export const mockCISTable = {
  session_id: 999,
  asset_id: 1,
  asset_name: "Demo-CoreSwitch",
  target_ip: "192.168.1.1",
  audit_date: new Date().toISOString(),
  benchmark_version: "CIS Cisco IOS 15 Benchmark v4.1.1",
  sections: [
    { section: "1.1.1", recommendation: "Enable 'aaa new-model'", set_correctly: true },
    { section: "1.1.2", recommendation: "Enable 'aaa authentication login'", set_correctly: true },
    { section: "1.1.3", recommendation: "Enable 'aaa authentication enable default'", set_correctly: false },
    { section: "1.1.4", recommendation: "Set 'login authentication for 'line con 0'", set_correctly: true },
    { section: "1.1.5", recommendation: "Set 'login authentication for 'line tty'", set_correctly: true },
    { section: "1.1.6", recommendation: "Set 'login authentication for 'line vty'", set_correctly: true },
    { section: "1.1.7", recommendation: "Set 'aaa accounting' to log all privileged use commands using 'commands 15'", set_correctly: true },
    { section: "1.1.8", recommendation: "Set 'aaa accounting connection'", set_correctly: false },
    { section: "1.1.9", recommendation: "Set 'aaa accounting exec'", set_correctly: false },
    { section: "1.1.10", recommendation: "Set 'aaa accounting network'", set_correctly: true },
    { section: "1.1.11", recommendation: "Set 'aaa accounting system'", set_correctly: true },
    { section: "1.2.1", recommendation: "Set 'privilege 1' for local users", set_correctly: true },
    { section: "1.2.2", recommendation: "Set 'transport input ssh' for 'line vty' connections", set_correctly: true },
    { section: "1.2.4", recommendation: "Create 'access-list' for use with 'line vty'", set_correctly: true },
    { section: "1.2.5", recommendation: "Set 'access-class' for 'line vty'", set_correctly: true },
    { section: "1.3.1", recommendation: "Set the 'banner-text' for 'banner exec'", set_correctly: true },
    { section: "1.3.2", recommendation: "Set the 'banner-text' for 'banner login'", set_correctly: true },
    { section: "1.3.3", recommendation: "Set the 'banner-text' for 'banner motd'", set_correctly: true },
    { section: "1.4.1", recommendation: "Set 'password' for 'enable secret'", set_correctly: true },
    { section: "1.4.2", recommendation: "Enable 'service password-encryption'", set_correctly: true },
    { section: "1.4.3", recommendation: "Set 'username secret' for all local users", set_correctly: false },
    { section: "1.5.1", recommendation: "Set 'no snmp-server' to disable SNMP when unused", set_correctly: true },
    { section: "1.5.2", recommendation: "Unset 'private' for 'snmp-server community'", set_correctly: true },
    { section: "1.5.3", recommendation: "Unset 'public' for 'snmp-server community'", set_correctly: true },
    { section: "1.5.4", recommendation: "Do not set 'RW' for any 'snmp-server community'", set_correctly: true },
    { section: "1.5.5", recommendation: "Set the ACL for each 'snmp-server community'", set_correctly: true },
    { section: "1.5.6", recommendation: "Create an 'access-list' for use with SNMP", set_correctly: true },
    { section: "1.5.7", recommendation: "Set 'snmp-server host' when using SNMP", set_correctly: true },
    { section: "1.5.8", recommendation: "Set 'snmp-server enable traps snmp'", set_correctly: true },
    { section: "1.5.9", recommendation: "Set 'priv' for each 'snmp-server group' using SNMPv3", set_correctly: true },
    { section: "1.5.10", recommendation: "Require 'aes 128' as minimum for 'snmp-server user' when using SNMPv3", set_correctly: true },
    { section: "2.1.1.1.1", recommendation: "Set the 'hostname'", set_correctly: true },
    { section: "2.1.1.1.2", recommendation: "Set the 'ip domain-name'", set_correctly: true },
    { section: "2.1.1.1.3", recommendation: "Set 'modulus' to greater than or equal to 2048 for 'crypto key generate rsa'", set_correctly: true },
    { section: "2.1.1.1.4", recommendation: "Set 'seconds' for 'ip ssh timeout'", set_correctly: true },
    { section: "2.1.1.1.5", recommendation: "Set maximimum value for 'ip ssh authentication-retries'", set_correctly: true },
    { section: "2.1.1.2", recommendation: "Set version 2 for 'ip ssh version'", set_correctly: true },
    { section: "2.1.2", recommendation: "Set 'no cdp run'", set_correctly: true },
    { section: "2.1.3", recommendation: "Set 'no ip bootp server'", set_correctly: true },
    { section: "2.1.4", recommendation: "Set 'no service dhcp'", set_correctly: true },
    { section: "2.1.5", recommendation: "Set 'no ip identd'", set_correctly: true },
    { section: "2.1.6", recommendation: "Set 'service tcp-keepalives-in'", set_correctly: true },
    { section: "2.1.8", recommendation: "Set 'no service pad'", set_correctly: true },
    { section: "2.2.1", recommendation: "Set 'logging on'", set_correctly: true },
    { section: "2.2.2", recommendation: "Set 'buffer size' for 'logging buffered'", set_correctly: true },
    { section: "2.2.3", recommendation: "Set 'logging console critical'", set_correctly: true },
    { section: "2.2.4", recommendation: "Set IP address for 'logging host'", set_correctly: true },
    { section: "2.2.5", recommendation: "Set 'logging trap informational'", set_correctly: true },
    { section: "2.2.6", recommendation: "Set 'service timestamps debug datetime'", set_correctly: true },
    { section: "2.2.7", recommendation: "Set 'logging source interface'", set_correctly: true },
    { section: "2.3.1.1", recommendation: "Set 'ntp authenticate'", set_correctly: true },
    { section: "2.3.1.2", recommendation: "Set 'ntp authentication-key'", set_correctly: true },
    { section: "2.3.1.3", recommendation: "Set the 'ntp trusted-key'", set_correctly: true },
    { section: "2.3.1.4", recommendation: "Set 'key' for each 'ntp server'", set_correctly: true },
    { section: "2.3.2", recommendation: "Set 'ip address' for 'ntp server'", set_correctly: true },
    { section: "2.4.1", recommendation: "Create a single 'interface loopback'", set_correctly: true },
    { section: "2.4.2", recommendation: "Set AAA 'source-interface'", set_correctly: false },
    { section: "2.4.3", recommendation: "Set 'ntp source' to Loopback Interface", set_correctly: true },
    { section: "2.4.4", recommendation: "Set 'ip tftp source-interface' to the Loopback Interface", set_correctly: true },
    { section: "3.1.1", recommendation: "Set 'no ip source-route'", set_correctly: true },
    { section: "3.1.2", recommendation: "Set 'no ip proxy-arp'", set_correctly: true },
    { section: "3.1.3", recommendation: "Set 'no interface tunnel'", set_correctly: true },
    { section: "3.1.4", recommendation: "Set 'ip verify unicast source reachable-via'", set_correctly: false },
    { section: "3.2.1", recommendation: "Set 'ip access-list extended' to Forbid Private Source Addresses from External Networks", set_correctly: true },
    { section: "3.2.2", recommendation: "Set inbound 'ip access-group' on the External Interface", set_correctly: true },
    { section: "3.3.1.1", recommendation: "Set 'key chain'", set_correctly: true },
    { section: "3.3.1.2", recommendation: "Set 'key'", set_correctly: true },
    { section: "3.3.1.3", recommendation: "Set 'key-string'", set_correctly: true },
    { section: "3.3.1.4", recommendation: "Set 'address-family ipv4 autonomous-system'", set_correctly: true },
    { section: "3.3.1.5", recommendation: "Set 'af-interface default'", set_correctly: true },
    { section: "3.3.1.6", recommendation: "Set 'authentication key-chain'", set_correctly: true },
    { section: "3.3.1.7", recommendation: "Set 'authentication mode md5'", set_correctly: true },
    { section: "3.3.1.8", recommendation: "Set 'ip authentication key-chain eigrp'", set_correctly: true },
    { section: "3.3.1.9", recommendation: "Set 'ip authentication mode eigrp'", set_correctly: true },
    { section: "3.3.2.1", recommendation: "Set 'authentication message-digest' for OSPF area", set_correctly: true },
    { section: "3.3.2.2", recommendation: "Set 'ip ospf message-digest-key md5'", set_correctly: true },
    { section: "3.3.3.1", recommendation: "Set 'key chain'", set_correctly: true },
    { section: "3.3.3.2", recommendation: "Set 'key'", set_correctly: true },
    { section: "3.3.3.3", recommendation: "Set 'key-string'", set_correctly: true },
    { section: "3.3.3.4", recommendation: "Set 'ip rip authentication key-chain'", set_correctly: true },
    { section: "3.3.3.5", recommendation: "Set 'ip rip authentication mode' to 'md5'", set_correctly: true },
    { section: "3.3.4.1", recommendation: "Set 'neighbor password'", set_correctly: false }
  ],
  summary: {
    total_checks: 82,
    passed: 74,
    failed: 8,
    compliance_percentage: 90.24
  }
};
