# Production image for the License Server admin UI.
# Two stages: build the Vite bundle, then serve it from nginx.
#
# The bundle is built WITHOUT VITE_LICENSE_API_URL on purpose, so the client
# uses relative paths (/api/..., /health) and nginx proxies them to the license
# server over the internal docker network — same origin, no CORS, and no server
# address baked into the JavaScript.
FROM docker.arvancloud.ir/node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM docker.arvancloud.ir/nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
