"""add os_guessed column to discovered_hosts

Revision ID: 0d5118f3f5fb
Revises: 72ec199c7f01
Create Date: 2025-12-30 02:57:50.510721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5118f3f5fb'
down_revision: Union[str, Sequence[str], None] = '72ec199c7f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovered_hosts', sa.Column('os_guessed', sa.String(length=255), nullable=True, comment='OS guessed from service detection (-sV)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovered_hosts', 'os_guessed')
    # ### end Alembic commands ###
