"""update for Fortigate Hardening

Revision ID: 0f9dda3c6110
Revises: add_module_audit_logs
Create Date: 2026-02-01 20:26:14.000222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f9dda3c6110'
down_revision: Union[str, Sequence[str], None] = 'add_module_audit_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_logs', 'asset_name',
               existing_type=sa.VARCHAR(length=256),
               comment='Name of the affected asset for readability',
               existing_comment='Name of the affected asset',
               existing_nullable=True)
    op.alter_column('asset_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional context (field changes, import counts, etc.)',
               existing_comment='Additional context',
               existing_nullable=True)
    op.alter_column('asset_requirement_logs', 'entity_name',
               existing_type=sa.VARCHAR(length=256),
               comment='Name of the affected entity for readability',
               existing_comment='Name of the affected entity',
               existing_nullable=True)
    op.alter_column('asset_requirement_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional context (import counts, field changes, etc.)',
               existing_comment='Additional context',
               existing_nullable=True)
    op.alter_column('audit_module_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional context (compliance results, etc.)',
               existing_comment='Additional context',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_module_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional context',
               existing_comment='Additional context (compliance results, etc.)',
               existing_nullable=True)
    op.alter_column('asset_requirement_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional context',
               existing_comment='Additional context (import counts, field changes, etc.)',
               existing_nullable=True)
    op.alter_column('asset_requirement_logs', 'entity_name',
               existing_type=sa.VARCHAR(length=256),
               comment='Name of the affected entity',
               existing_comment='Name of the affected entity for readability',
               existing_nullable=True)
    op.alter_column('asset_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional context',
               existing_comment='Additional context (field changes, import counts, etc.)',
               existing_nullable=True)
    op.alter_column('asset_logs', 'asset_name',
               existing_type=sa.VARCHAR(length=256),
               comment='Name of the affected asset',
               existing_comment='Name of the affected asset for readability',
               existing_nullable=True)
    # ### end Alembic commands ###
