"""Add audit tables for security compliance checking

Revision ID: 3e436e55ff99
Revises: c9f1e2d3a4b5
Create Date: 2025-12-03 16:32:17.541953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e436e55ff99'
down_revision: Union[str, Sequence[str], None] = 'c9f1e2d3a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('device_type', sa.Enum('CISCO', 'LINUX', 'WINDOWS', 'FORTINET', name='devicetype'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_templates_id'), 'audit_templates', ['id'], unique=False)
    op.create_table('audit_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('check_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['audit_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_checks_id'), 'audit_checks', ['id'], unique=False)
    op.create_table('audit_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('target_ip', sa.String(length=50), nullable=False),
    sa.Column('device_type', sa.Enum('CISCO', 'LINUX', 'WINDOWS', 'FORTINET', name='devicetype'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('passed_checks', sa.Integer(), nullable=True),
    sa.Column('failed_checks', sa.Integer(), nullable=True),
    sa.Column('error_checks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_inventory.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['audit_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_sessions_id'), 'audit_sessions', ['id'], unique=False)
    op.create_table('audit_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'NOT_APPLICABLE', 'ERROR', name='checkstatus'), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['audit_checks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['audit_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_results_id'), 'audit_results', ['id'], unique=False)
    op.alter_column('asset_inventory', 'discovered_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Fields populated by auto-discovery (JSON: {field_name: true})',
               existing_comment='Fields populated by auto-discovery',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_inventory', 'discovered_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Fields populated by auto-discovery',
               existing_comment='Fields populated by auto-discovery (JSON: {field_name: true})',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('ix_audit_results_id'), table_name='audit_results')
    op.drop_table('audit_results')
    op.drop_index(op.f('ix_audit_sessions_id'), table_name='audit_sessions')
    op.drop_table('audit_sessions')
    op.drop_index(op.f('ix_audit_checks_id'), table_name='audit_checks')
    op.drop_table('audit_checks')
    op.drop_index(op.f('ix_audit_templates_id'), table_name='audit_templates')
    op.drop_table('audit_templates')
    # ### end Alembic commands ###
