"""add_user_permissions_table

Revision ID: 4213a059f843
Revises: 8d0ba5279f2e
Create Date: 2025-11-25 19:40:40.011983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4213a059f843'
down_revision: Union[str, Sequence[str], None] = '8d0ba5279f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for permission record'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Reference to users table'),
    sa.Column('module', sa.Enum('DASHBOARD', 'ASSET_REQUIREMENT', 'ASSET_LIST', 'ASSET_AUTO_DISCOVERY', 'USER_MANAGEMENT', 'AUDITING', 'HARDENING', 'LOGS', name='moduleenum'), nullable=False, comment='Which module this permission applies to'),
    sa.Column('can_read', sa.Boolean(), nullable=False, comment='Can view/read data in this module'),
    sa.Column('can_write', sa.Boolean(), nullable=False, comment='Can create/edit data in this module'),
    sa.Column('can_delete', sa.Boolean(), nullable=False, comment='Can delete data in this module'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module', name='unique_user_module')
    )
    op.create_index(op.f('ix_user_permissions_module'), 'user_permissions', ['module'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_module'), table_name='user_permissions')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
