"""fix foreign key ondelete constraints

Revision ID: 7c8c6fdd501f
Revises: 9fe7cf0e0eb5
Create Date: 2026-05-05 08:48:23.089448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8c6fdd501f'
down_revision: Union[str, Sequence[str], None] = '9fe7cf0e0eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE audit_sessions ADD COLUMN IF NOT EXISTS job_name VARCHAR(200)")
    op.drop_constraint(op.f('audit_sessions_asset_id_fkey'), 'audit_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'audit_sessions', 'asset_inventory', ['asset_id'], ['id'], ondelete='SET NULL')
    op.execute("ALTER TABLE discovered_hosts ADD COLUMN IF NOT EXISTS os_guessed VARCHAR(255)")
    op.execute("ALTER TABLE discovery_scans ADD COLUMN IF NOT EXISTS version_detection INTEGER")
    op.alter_column('discovery_scans', 'ports',
               existing_type=sa.VARCHAR(length=255),
               comment="Ports to scan (e.g., '80,443,8080' or '1-1000' or 'top1000')",
               existing_comment='Ports to scan',
               existing_nullable=True)
    op.alter_column('hardening_actions', 'asset_id',
               existing_type=sa.INTEGER(),
               comment='Related asset id',
               existing_nullable=False)
    op.drop_constraint(op.f('hardening_actions_asset_id_fkey'), 'hardening_actions', type_='foreignkey')
    op.create_foreign_key(None, 'hardening_actions', 'asset_inventory', ['asset_id'], ['id'], ondelete='CASCADE')
    # Some environments enforce protocols.name uniqueness via a unique index
    # rather than a named unique constraint, so drop the constraint defensively.
    op.execute("ALTER TABLE protocols DROP CONSTRAINT IF EXISTS protocols_name_key")
    op.drop_index(op.f('ix_protocols_name'), table_name='protocols')
    op.create_index(op.f('ix_protocols_name'), 'protocols', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protocols_name'), table_name='protocols')
    op.create_index(op.f('ix_protocols_name'), 'protocols', ['name'], unique=False)
    op.create_unique_constraint(op.f('protocols_name_key'), 'protocols', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'hardening_actions', type_='foreignkey')
    op.create_foreign_key(op.f('hardening_actions_asset_id_fkey'), 'hardening_actions', 'asset_inventory', ['asset_id'], ['id'])
    op.alter_column('hardening_actions', 'asset_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Related asset id',
               existing_nullable=False)
    op.alter_column('discovery_scans', 'ports',
               existing_type=sa.VARCHAR(length=255),
               comment='Ports to scan',
               existing_comment="Ports to scan (e.g., '80,443,8080' or '1-1000' or 'top1000')",
               existing_nullable=True)
    op.drop_column('discovery_scans', 'version_detection')
    op.drop_column('discovered_hosts', 'os_guessed')
    op.drop_constraint(None, 'audit_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('audit_sessions_asset_id_fkey'), 'audit_sessions', 'asset_inventory', ['asset_id'], ['id'])
    op.drop_column('audit_sessions', 'job_name')
    # ### end Alembic commands ###
