"""Create asset management tables

Revision ID: 8d0ba5279f2e
Revises: 
Create Date: 2025-11-24 16:39:17.977152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0ba5279f2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier'),
    sa.Column('type_name', sa.String(length=100), nullable=False, comment='Asset type name (e.g., Firewall)'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Category (Security, Network, Infrastructure, etc.)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_types_category'), 'asset_types', ['category'], unique=False)
    op.create_index(op.f('ix_asset_types_type_name'), 'asset_types', ['type_name'], unique=True)
    op.create_table('network_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier'),
    sa.Column('zone_name', sa.String(length=100), nullable=False, comment='Network zone name (e.g., DMZ, Internal, Management)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of the zone purpose and characteristics'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_zones_zone_name'), 'network_zones', ['zone_name'], unique=True)
    op.create_table('os_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier'),
    sa.Column('os_name', sa.String(length=100), nullable=False, comment='Operating system name (e.g., Windows Server, Ubuntu, FortiOS)'),
    sa.Column('os_version', sa.String(length=50), nullable=True, comment='Version information (e.g., 2019, 22.04, 7.2)'),
    sa.Column('os_family', sa.String(length=50), nullable=True, comment='OS family or category (e.g., Windows, Linux, Network OS)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional information about this OS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_catalog_os_family'), 'os_catalog', ['os_family'], unique=False)
    op.create_index(op.f('ix_os_catalog_os_name'), 'os_catalog', ['os_name'], unique=False)
    op.create_table('vendor_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier'),
    sa.Column('vendor_name', sa.String(length=200), nullable=False, comment='Vendor or manufacturer name (e.g., Cisco, HP, Dell)'),
    sa.Column('vendor_type', sa.String(length=100), nullable=True, comment='Type of vendor (e.g., Network, Security, Server, Storage)'),
    sa.Column('website', sa.String(length=255), nullable=True, comment='Vendor website URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional information about the vendor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_catalog_vendor_name'), 'vendor_catalog', ['vendor_name'], unique=True)
    op.create_index(op.f('ix_vendor_catalog_vendor_type'), 'vendor_catalog', ['vendor_type'], unique=False)
    op.create_table('asset_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for location'),
    sa.Column('site_name', sa.String(length=200), nullable=False, comment='Site or building name (e.g., Main DC, Branch Office)'),
    sa.Column('rack_name', sa.String(length=100), nullable=True, comment='Rack identifier (e.g., Rack-12, R-A-05)'),
    sa.Column('room', sa.String(length=100), nullable=True, comment='Room name or number (e.g., Server Room A, Room 204)'),
    sa.Column('floor', sa.String(length=50), nullable=True, comment='Floor number or name (e.g., 2nd Floor, Basement)'),
    sa.Column('network_zone', sa.String(length=100), nullable=True, comment='Network zone or segment (e.g., DMZ, Internal, Management)'),
    sa.Column('vlan_id', sa.Integer(), nullable=True, comment='VLAN identifier (e.g., 100, 200)'),
    sa.Column('subnet', sa.String(length=50), nullable=True, comment='Network subnet in CIDR notation (e.g., 10.0.0.0/24, 192.168.1.0/24)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional notes or description about this location'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Reference to users table - determines which user owns this location record'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_locations_network_zone'), 'asset_locations', ['network_zone'], unique=False)
    op.create_index(op.f('ix_asset_locations_site_name'), 'asset_locations', ['site_name'], unique=False)
    op.create_index(op.f('ix_asset_locations_user_id'), 'asset_locations', ['user_id'], unique=False)
    op.create_table('asset_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for asset owner'),
    sa.Column('full_name', sa.String(length=200), nullable=False, comment='Full name of the asset owner'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='Department or team name (e.g., IT, Security, Network)'),
    sa.Column('role', sa.String(length=100), nullable=True, comment='Job role or position (e.g., Network Manager, Security Admin)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Contact email address'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Contact phone number'),
    sa.Column('responsibility_level', sa.String(length=50), nullable=True, comment='Level of responsibility (e.g., Primary, Secondary, Backup)'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Reference to users table - determines which user owns this owner record'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_owners_department'), 'asset_owners', ['department'], unique=False)
    op.create_index(op.f('ix_asset_owners_email'), 'asset_owners', ['email'], unique=False)
    op.create_index(op.f('ix_asset_owners_full_name'), 'asset_owners', ['full_name'], unique=False)
    op.create_index(op.f('ix_asset_owners_user_id'), 'asset_owners', ['user_id'], unique=False)
    op.create_table('asset_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier (asset_id in forms)'),
    sa.Column('asset_name', sa.String(length=200), nullable=False, comment='Name of the asset (e.g., Core-Switch-01, FW-Main)'),
    sa.Column('hostname', sa.String(length=200), nullable=True, comment='Network hostname'),
    sa.Column('asset_type_id', sa.Integer(), nullable=False, comment='FK to asset_types (Firewall, Router, Switch, etc.)'),
    sa.Column('asset_role', sa.String(length=200), nullable=True, comment='Role or purpose of the asset (e.g., Core Network, DMZ Gateway)'),
    sa.Column('manufacturer', sa.String(length=200), nullable=True, comment='Vendor/manufacturer name (e.g., Cisco, HP, Dell)'),
    sa.Column('model', sa.String(length=200), nullable=True, comment='Model name or number (e.g., Catalyst 9300, ProLiant DL380)'),
    sa.Column('serial_number', sa.String(length=200), nullable=True, comment='Serial number (should be unique)'),
    sa.Column('os_name', sa.String(length=100), nullable=True, comment='Operating system name (e.g., Windows Server, Ubuntu, FortiOS)'),
    sa.Column('os_version', sa.String(length=50), nullable=True, comment='OS version (e.g., 2019, 22.04, 7.2)'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP address (e.g., 10.0.0.1, 192.168.1.100)'),
    sa.Column('mac_address', sa.String(length=50), nullable=True, comment='MAC address (e.g., 00:11:22:33:44:55)'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='FK to asset_locations (physical/logical location)'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='FK to asset_owners (person responsible for asset)'),
    sa.Column('status', sa.Enum('ACTIVE', 'STANDBY', 'DECOMMISSIONED', 'UNKNOWN', name='statusenum'), nullable=False, comment='Asset status (active, standby, decommissioned, unknown)'),
    sa.Column('confidentiality_level', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'CRITICAL', name='confidentialitylevelenum'), nullable=True, comment='Data classification (public, internal, confidential, critical)'),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevelenum'), nullable=True, comment='Risk assessment (low, medium, high, critical)'),
    sa.Column('last_audit_date', sa.Date(), nullable=True, comment='Date of last audit or review'),
    sa.Column('last_patch_date', sa.Date(), nullable=True, comment='Date of last security patch or update'),
    sa.Column('asset_value', sa.Numeric(precision=15, scale=2), nullable=True, comment='Financial value of the asset (with 2 decimal places)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional notes or description'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK to users - determines which user owns this asset'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['asset_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['asset_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_inventory_asset_name'), 'asset_inventory', ['asset_name'], unique=False)
    op.create_index(op.f('ix_asset_inventory_asset_type_id'), 'asset_inventory', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_asset_inventory_confidentiality_level'), 'asset_inventory', ['confidentiality_level'], unique=False)
    op.create_index(op.f('ix_asset_inventory_hostname'), 'asset_inventory', ['hostname'], unique=False)
    op.create_index(op.f('ix_asset_inventory_ip_address'), 'asset_inventory', ['ip_address'], unique=False)
    op.create_index(op.f('ix_asset_inventory_location_id'), 'asset_inventory', ['location_id'], unique=False)
    op.create_index(op.f('ix_asset_inventory_mac_address'), 'asset_inventory', ['mac_address'], unique=False)
    op.create_index(op.f('ix_asset_inventory_manufacturer'), 'asset_inventory', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_asset_inventory_os_name'), 'asset_inventory', ['os_name'], unique=False)
    op.create_index(op.f('ix_asset_inventory_owner_id'), 'asset_inventory', ['owner_id'], unique=False)
    op.create_index(op.f('ix_asset_inventory_risk_level'), 'asset_inventory', ['risk_level'], unique=False)
    op.create_index(op.f('ix_asset_inventory_serial_number'), 'asset_inventory', ['serial_number'], unique=True)
    op.create_index(op.f('ix_asset_inventory_status'), 'asset_inventory', ['status'], unique=False)
    op.create_index(op.f('ix_asset_inventory_user_id'), 'asset_inventory', ['user_id'], unique=False)
    op.create_table('asset_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for dependency record'),
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='The asset that has a dependency (dependent asset)'),
    sa.Column('depends_on_id', sa.Integer(), nullable=False, comment='The asset that is depended upon (dependency target)'),
    sa.Column('relation_type', sa.Enum('NETWORK_LINK', 'APP_DEPENDENCY', 'BACKUP_LINK', 'POWER_SOURCE', 'LOGICAL_CONNECTION', name='relationtypeenum'), nullable=False, comment='Type of relationship (network_link, app_dependency, backup_link, power_source, logical_connection)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional notes or details about this dependency'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_id'], ['asset_inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_dependencies_asset_id'), 'asset_dependencies', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_dependencies_depends_on_id'), 'asset_dependencies', ['depends_on_id'], unique=False)
    op.create_index(op.f('ix_asset_dependencies_relation_type'), 'asset_dependencies', ['relation_type'], unique=False)
    op.create_table('asset_security_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for security status record'),
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='Reference to asset_inventory (one-to-one relationship)'),
    sa.Column('antivirus_installed', sa.Boolean(), nullable=False, comment='Whether antivirus software is installed'),
    sa.Column('antivirus_status', sa.String(length=50), nullable=True, comment='Status of antivirus (e.g., Active, Outdated, Disabled, Not Applicable)'),
    sa.Column('firewall_enabled', sa.Boolean(), nullable=False, comment='Whether firewall is enabled'),
    sa.Column('last_patch_date', sa.Date(), nullable=True, comment='Date of last security patch or update'),
    sa.Column('backup_enabled', sa.Boolean(), nullable=False, comment='Whether backup is configured and enabled'),
    sa.Column('vulnerability_score', sa.Float(), nullable=True, comment='Vulnerability score (0-10, CVSS or custom scale)'),
    sa.Column('compliance_status', sa.String(length=50), nullable=True, comment='Compliance state (e.g., Compliant, Non-Compliant, Partially Compliant, Under Review)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional security notes or observations'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_security_status_asset_id'), 'asset_security_status', ['asset_id'], unique=True)
    op.create_index(op.f('ix_asset_security_status_compliance_status'), 'asset_security_status', ['compliance_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_security_status_compliance_status'), table_name='asset_security_status')
    op.drop_index(op.f('ix_asset_security_status_asset_id'), table_name='asset_security_status')
    op.drop_table('asset_security_status')
    op.drop_index(op.f('ix_asset_dependencies_relation_type'), table_name='asset_dependencies')
    op.drop_index(op.f('ix_asset_dependencies_depends_on_id'), table_name='asset_dependencies')
    op.drop_index(op.f('ix_asset_dependencies_asset_id'), table_name='asset_dependencies')
    op.drop_table('asset_dependencies')
    op.drop_index(op.f('ix_asset_inventory_user_id'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_status'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_serial_number'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_risk_level'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_owner_id'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_os_name'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_manufacturer'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_mac_address'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_location_id'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_ip_address'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_hostname'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_confidentiality_level'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_asset_type_id'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_asset_name'), table_name='asset_inventory')
    op.drop_table('asset_inventory')
    op.drop_index(op.f('ix_asset_owners_user_id'), table_name='asset_owners')
    op.drop_index(op.f('ix_asset_owners_full_name'), table_name='asset_owners')
    op.drop_index(op.f('ix_asset_owners_email'), table_name='asset_owners')
    op.drop_index(op.f('ix_asset_owners_department'), table_name='asset_owners')
    op.drop_table('asset_owners')
    op.drop_index(op.f('ix_asset_locations_user_id'), table_name='asset_locations')
    op.drop_index(op.f('ix_asset_locations_site_name'), table_name='asset_locations')
    op.drop_index(op.f('ix_asset_locations_network_zone'), table_name='asset_locations')
    op.drop_table('asset_locations')
    op.drop_index(op.f('ix_vendor_catalog_vendor_type'), table_name='vendor_catalog')
    op.drop_index(op.f('ix_vendor_catalog_vendor_name'), table_name='vendor_catalog')
    op.drop_table('vendor_catalog')
    op.drop_index(op.f('ix_os_catalog_os_name'), table_name='os_catalog')
    op.drop_index(op.f('ix_os_catalog_os_family'), table_name='os_catalog')
    op.drop_table('os_catalog')
    op.drop_index(op.f('ix_network_zones_zone_name'), table_name='network_zones')
    op.drop_table('network_zones')
    op.drop_index(op.f('ix_asset_types_type_name'), table_name='asset_types')
    op.drop_index(op.f('ix_asset_types_category'), table_name='asset_types')
    op.drop_table('asset_types')
    # ### end Alembic commands ###
