"""Add new feature

Revision ID: 91159b1eaed1
Revises: a843df816d1c
Create Date: 2025-12-10 14:56:54.859624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91159b1eaed1'
down_revision: Union[str, Sequence[str], None] = 'a843df816d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_types', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique identifier',
               existing_comment='شناسه یکتا',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('asset_types_id_seq'::regclass)"))
    op.alter_column('asset_types', 'type_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Asset type name (e.g., Firewall)',
               existing_comment='نام نوع asset (مثلاً Firewall)',
               existing_nullable=False)
    op.alter_column('asset_types', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='Category (Security, Network, Infrastructure, etc.)',
               existing_comment='دسته\u200cبندی (Security, Network, Infrastructure, ...)',
               existing_nullable=False)
    op.alter_column('asset_types', 'description',
               existing_type=sa.TEXT(),
               comment='Optional description',
               existing_comment='توضیحات اختیاری',
               existing_nullable=True)
    op.alter_column('discovery_scans', 'target',
               existing_type=sa.VARCHAR(length=255),
               comment='Target IP, CIDR range, or IP range (e.g., 192.168.1.0/24, 192.168.1.1-192.168.1.50)',
               existing_comment='Target IP, CIDR range, or IP range',
               existing_nullable=False)
    op.alter_column('discovery_scans', 'scan_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Scan type: all_ports, well_known_ports, custom_ports',
               existing_comment='Scan intensity: basic, detailed, full',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discovery_scans', 'scan_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Scan intensity: basic, detailed, full',
               existing_comment='Scan type: all_ports, well_known_ports, custom_ports',
               existing_nullable=False)
    op.alter_column('discovery_scans', 'target',
               existing_type=sa.VARCHAR(length=255),
               comment='Target IP, CIDR range, or IP range',
               existing_comment='Target IP, CIDR range, or IP range (e.g., 192.168.1.0/24, 192.168.1.1-192.168.1.50)',
               existing_nullable=False)
    op.alter_column('asset_types', 'description',
               existing_type=sa.TEXT(),
               comment='توضیحات اختیاری',
               existing_comment='Optional description',
               existing_nullable=True)
    op.alter_column('asset_types', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='دسته\u200cبندی (Security, Network, Infrastructure, ...)',
               existing_comment='Category (Security, Network, Infrastructure, etc.)',
               existing_nullable=False)
    op.alter_column('asset_types', 'type_name',
               existing_type=sa.VARCHAR(length=100),
               comment='نام نوع asset (مثلاً Firewall)',
               existing_comment='Asset type name (e.g., Firewall)',
               existing_nullable=False)
    op.alter_column('asset_types', 'id',
               existing_type=sa.INTEGER(),
               comment='شناسه یکتا',
               existing_comment='Unique identifier',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('asset_types_id_seq'::regclass)"))
    # ### end Alembic commands ###
