"""Add SET NULL to audit_sessions.asset_id FK

Revision ID: 9fe7cf0e0eb5
Revises: c3d4e5f6a7b8
Create Date: 2026-05-05 04:42:16.186912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe7cf0e0eb5'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_sessions', 'job_name',
               existing_type=sa.VARCHAR(length=200),
               comment='User-friendly job name for the audit',
               existing_nullable=True)
    op.drop_constraint(op.f('audit_sessions_asset_id_fkey'), 'audit_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'audit_sessions', 'asset_inventory', ['asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('audit_sessions_asset_id_fkey'), 'audit_sessions', 'asset_inventory', ['asset_id'], ['id'])
    op.alter_column('audit_sessions', 'job_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='User-friendly job name for the audit',
               existing_nullable=True)
    # ### end Alembic commands ###
