"""add discovery models for scan persistence and audit

Revision ID: e4de134c385b
Revises: 3e436e55ff99
Create Date: 2025-12-04 13:43:59.426636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4de134c385b'
down_revision: Union[str, Sequence[str], None] = '3e436e55ff99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_inventory', 'discovered_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Fields populated by auto-discovery (JSON: {field_name: true})',
               existing_comment='Fields populated by auto-discovery',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_inventory', 'discovered_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Fields populated by auto-discovery',
               existing_comment='Fields populated by auto-discovery (JSON: {field_name: true})',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###
