"""add discovery models for scan persistence and audit

Revision ID: e4de134c385b
Revises: 3e436e55ff99
Create Date: 2025-12-04 13:43:59.426636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4de134c385b'
down_revision: Union[str, Sequence[str], None] = '3e436e55ff99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create discovery_scans table
    op.create_table('discovery_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=50), nullable=False, comment='Unique 8-character scan identifier'),
    sa.Column('job_name', sa.String(length=200), nullable=True, comment='User-friendly job name for the scan'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User who initiated the scan'),
    sa.Column('target', sa.String(length=255), nullable=False, comment='Target IP, CIDR range, or IP range'),
    sa.Column('scan_type', sa.String(length=20), nullable=False, comment='Scan type: all_ports, well_known_ports, custom_ports'),
    sa.Column('ports', sa.String(length=255), nullable=True, comment='Ports to scan'),
    sa.Column('protocol', sa.String(length=20), nullable=True, comment='Protocol to scan: TCP, UDP, or BOTH'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Scan status: running, completed, failed'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='Scan start timestamp'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Scan completion timestamp'),
    sa.Column('hosts_discovered', sa.Integer(), nullable=True, comment='Total number of hosts found in scan'),
    sa.Column('hosts_up', sa.Integer(), nullable=True, comment='Number of live/responsive hosts'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if scan failed'),
    sa.Column('results_json', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Complete scan results with discovered hosts'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_scans_scan_id'), 'discovery_scans', ['scan_id'], unique=True)
    op.create_index(op.f('ix_discovery_scans_job_name'), 'discovery_scans', ['job_name'], unique=False)
    op.create_index(op.f('ix_discovery_scans_user_id'), 'discovery_scans', ['user_id'], unique=False)
    op.create_index(op.f('ix_discovery_scans_target'), 'discovery_scans', ['target'], unique=False)
    op.create_index(op.f('ix_discovery_scans_status'), 'discovery_scans', ['status'], unique=False)
    op.create_index(op.f('ix_discovery_scans_started_at'), 'discovery_scans', ['started_at'], unique=False)

    # Create discovered_hosts table
    op.create_table('discovered_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=50), nullable=False, comment='Scan that discovered this host'),
    sa.Column('ip_address', sa.String(length=50), nullable=False, comment='Discovered IP address'),
    sa.Column('mac_address', sa.String(length=17), nullable=True, comment='MAC address if discovered'),
    sa.Column('hostname', sa.String(length=255), nullable=True, comment='Hostname if discovered'),
    sa.Column('os_info', sa.String(length=255), nullable=True, comment='Operating system information'),
    sa.Column('os_accuracy', sa.Integer(), nullable=True, comment='OS detection accuracy percentage'),
    sa.Column('open_ports', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Array of discovered open ports with service info'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status: pending, approved, rejected, merged'),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True, comment='User who approved/rejected'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='When approved/rejected'),
    sa.Column('matched_asset_id', sa.Integer(), nullable=True, comment='Asset ID if matched/merged'),
    sa.Column('discovery_source', sa.String(length=50), nullable=True, comment='Discovery method: nmap, passive, manual, etc.'),
    sa.Column('state', sa.String(length=20), nullable=True, comment='Host state: up, down, unknown'),
    sa.Column('additional_info', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Additional discovered information'),
    sa.Column('discovered_at', sa.DateTime(), nullable=True, comment='When this host was discovered'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['scan_id'], ['discovery_scans.scan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_asset_id'], ['asset_inventory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_hosts_scan_id'), 'discovered_hosts', ['scan_id'], unique=False)
    op.create_index(op.f('ix_discovered_hosts_ip_address'), 'discovered_hosts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_discovered_hosts_mac_address'), 'discovered_hosts', ['mac_address'], unique=False)
    op.create_index(op.f('ix_discovered_hosts_status'), 'discovered_hosts', ['status'], unique=False)
    op.create_index(op.f('ix_discovered_hosts_matched_asset_id'), 'discovered_hosts', ['matched_asset_id'], unique=False)
    op.create_index(op.f('ix_discovered_hosts_discovered_at'), 'discovered_hosts', ['discovered_at'], unique=False)

    # Create discovery_applications table
    op.create_table('discovery_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=50), nullable=False, comment='Scan that provided the discovered data'),
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='Asset that was updated'),
    sa.Column('applied_by_user_id', sa.Integer(), nullable=True, comment='User who applied the discovery'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Discovered IP address that was applied'),
    sa.Column('fields_applied', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Fields that were updated with discovered values'),
    sa.Column('applied_at', sa.DateTime(), nullable=True, comment='When discovery was applied'),
    sa.ForeignKeyConstraint(['scan_id'], ['discovery_scans.scan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_applications_scan_id'), 'discovery_applications', ['scan_id'], unique=False)
    op.create_index(op.f('ix_discovery_applications_asset_id'), 'discovery_applications', ['asset_id'], unique=False)
    op.create_index(op.f('ix_discovery_applications_applied_by_user_id'), 'discovery_applications', ['applied_by_user_id'], unique=False)
    op.create_index(op.f('ix_discovery_applications_applied_at'), 'discovery_applications', ['applied_at'], unique=False)

    # Create discovery_audit_logs table
    op.create_table('discovery_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User who performed the action'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action type: scan_started, scan_completed, discovery_applied, etc.'),
    sa.Column('scan_id', sa.String(length=50), nullable=True, comment='Related scan ID'),
    sa.Column('asset_id', sa.Integer(), nullable=True, comment='Related asset ID'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Related IP address'),
    sa.Column('target', sa.String(length=255), nullable=True, comment='Scan target'),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Additional context as JSON'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Action status: success, failed, warning'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='When the action occurred'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_audit_logs_user_id'), 'discovery_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_discovery_audit_logs_action'), 'discovery_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_discovery_audit_logs_scan_id'), 'discovery_audit_logs', ['scan_id'], unique=False)
    op.create_index(op.f('ix_discovery_audit_logs_asset_id'), 'discovery_audit_logs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_discovery_audit_logs_timestamp'), 'discovery_audit_logs', ['timestamp'], unique=False)

    op.alter_column('asset_inventory', 'discovered_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Fields populated by auto-discovery (JSON: {field_name: true})',
               existing_comment='Fields populated by auto-discovery',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_inventory', 'discovered_fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Fields populated by auto-discovery',
               existing_comment='Fields populated by auto-discovery (JSON: {field_name: true})',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))

    # Drop tables in reverse order
    op.drop_index(op.f('ix_discovery_audit_logs_timestamp'), table_name='discovery_audit_logs')
    op.drop_index(op.f('ix_discovery_audit_logs_asset_id'), table_name='discovery_audit_logs')
    op.drop_index(op.f('ix_discovery_audit_logs_scan_id'), table_name='discovery_audit_logs')
    op.drop_index(op.f('ix_discovery_audit_logs_action'), table_name='discovery_audit_logs')
    op.drop_index(op.f('ix_discovery_audit_logs_user_id'), table_name='discovery_audit_logs')
    op.drop_table('discovery_audit_logs')

    op.drop_index(op.f('ix_discovery_applications_applied_at'), table_name='discovery_applications')
    op.drop_index(op.f('ix_discovery_applications_applied_by_user_id'), table_name='discovery_applications')
    op.drop_index(op.f('ix_discovery_applications_asset_id'), table_name='discovery_applications')
    op.drop_index(op.f('ix_discovery_applications_scan_id'), table_name='discovery_applications')
    op.drop_table('discovery_applications')

    op.drop_index(op.f('ix_discovered_hosts_discovered_at'), table_name='discovered_hosts')
    op.drop_index(op.f('ix_discovered_hosts_matched_asset_id'), table_name='discovered_hosts')
    op.drop_index(op.f('ix_discovered_hosts_status'), table_name='discovered_hosts')
    op.drop_index(op.f('ix_discovered_hosts_mac_address'), table_name='discovered_hosts')
    op.drop_index(op.f('ix_discovered_hosts_ip_address'), table_name='discovered_hosts')
    op.drop_index(op.f('ix_discovered_hosts_scan_id'), table_name='discovered_hosts')
    op.drop_table('discovered_hosts')

    op.drop_index(op.f('ix_discovery_scans_started_at'), table_name='discovery_scans')
    op.drop_index(op.f('ix_discovery_scans_status'), table_name='discovery_scans')
    op.drop_index(op.f('ix_discovery_scans_target'), table_name='discovery_scans')
    op.drop_index(op.f('ix_discovery_scans_user_id'), table_name='discovery_scans')
    op.drop_index(op.f('ix_discovery_scans_job_name'), table_name='discovery_scans')
    op.drop_index(op.f('ix_discovery_scans_scan_id'), table_name='discovery_scans')
    op.drop_table('discovery_scans')
    # ### end Alembic commands ###
