"""add_version_detection_to_discovery_scans

Revision ID: 66987062eb68
Revises: 6531c31543e4
Create Date: 2025-12-30 16:12:22.914344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66987062eb68'
down_revision: Union[str, Sequence[str], None] = '6531c31543e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_scans', sa.Column('version_detection', sa.Integer(), nullable=True, comment='Enable service version detection (-sV): 0=disabled, 1=enabled. WARNING: much slower'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_scans', 'version_detection')
    # ### end Alembic commands ###
