"""change_asset_user_id_to_set_null

Revision ID: b8ae20bc6d1a
Revises: 4213a059f843
Create Date: 2025-11-29 17:57:48.834258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ae20bc6d1a'
down_revision: Union[str, Sequence[str], None] = '4213a059f843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_inventory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='FK to users - determines which user owns this asset')
    op.drop_constraint(op.f('asset_inventory_user_id_fkey'), 'asset_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'asset_inventory', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_inventory', type_='foreignkey')
    op.create_foreign_key(op.f('asset_inventory_user_id_fkey'), 'asset_inventory', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('asset_inventory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='FK to users - determines which user owns this asset')
    # ### end Alembic commands ###
