"""update_audit_schema_for_cisco_cis

Revision ID: d71e1a4f5f3b
Revises: 7dee39989c1d
Create Date: 2025-12-15 23:15:16.119219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71e1a4f5f3b'
down_revision: Union[str, Sequence[str], None] = '7dee39989c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_checks', sa.Column('level', sa.String(length=10), nullable=True))
    op.add_column('audit_checks', sa.Column('rationale', sa.Text(), nullable=True))
    op.add_column('audit_checks', sa.Column('remediation', sa.Text(), nullable=True))
    op.drop_column('audit_checks', 'command')
    op.drop_column('audit_checks', 'expected_output')
    op.add_column('audit_results', sa.Column('check_number', sa.String(length=20), nullable=True))
    op.add_column('audit_results', sa.Column('check_title', sa.String(length=500), nullable=True))
    op.add_column('audit_results', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('audit_results', sa.Column('level', sa.String(length=10), nullable=True))
    op.add_column('audit_results', sa.Column('evidence_snippet', sa.Text(), nullable=True))
    op.alter_column('audit_results', 'check_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('audit_results', 'actual_output')
    op.drop_column('audit_results', 'error_message')
    op.add_column('audit_sessions', sa.Column('compliance_pct', sa.Float(), nullable=True))
    op.add_column('audit_sessions', sa.Column('weighted_compliance_pct', sa.Float(), nullable=True))
    op.add_column('audit_sessions', sa.Column('connection_error', sa.Text(), nullable=True))
    op.add_column('audit_sessions', sa.Column('turbo_dump', sa.Text(), nullable=True))
    op.alter_column('audit_sessions', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('audit_templates', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('audit_templates', sa.Column('profile', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_templates', 'profile')
    op.drop_column('audit_templates', 'is_active')
    op.alter_column('audit_sessions', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_sessions', 'turbo_dump')
    op.drop_column('audit_sessions', 'connection_error')
    op.drop_column('audit_sessions', 'weighted_compliance_pct')
    op.drop_column('audit_sessions', 'compliance_pct')
    op.add_column('audit_results', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_results', sa.Column('actual_output', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('audit_results', 'check_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_results', 'evidence_snippet')
    op.drop_column('audit_results', 'level')
    op.drop_column('audit_results', 'severity')
    op.drop_column('audit_results', 'check_title')
    op.drop_column('audit_results', 'check_number')
    op.add_column('audit_checks', sa.Column('expected_output', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_checks', sa.Column('command', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('audit_checks', 'remediation')
    op.drop_column('audit_checks', 'rationale')
    op.drop_column('audit_checks', 'level')
    # ### end Alembic commands ###
